### ISSUE TITLE
Exception when using no sound file for break warnings

### ISSUE THREAD

**Issue by PatrikSchulze** [EsotericSoftware/clippy#8]
`86:44 ERROR: Uncaught exception, exiting.
java.lang.NullPointerException
	at com.esotericsoftware.clippy.BreakWarning.playClip(BreakWarning.java:134)
	at com.esotericsoftware.clippy.BreakWarning$2$1.run(BreakWarning.java:103)`

I set all the break sound files to "null" but get this exception.

**Comment by NathanSweet** [comment]
Fixed, thanks! 7bd3b9c6ed769afc1710187d9ab22e06ece9b55b
New release is up with fix (2.33).
